### ISSUE TITLE
Input ports of mixer not drawn correctly when source is same

### ISSUE THREAD

**Issue by pwrstudio** [Moving-Castles/this-cursed-machine#176]
![Image](https://github.com/Moving-Castles/this-cursed-machine/assets/8209990/6f0ad141-959e-4101-b188-70ea74ea046d)

**Comment by manegame** [comment]
![Image](https://github.com/Moving-Castles/this-cursed-machine/assets/17074938/3adf4e03-fb1c-4fc2-b259-473def867cae)
![Image](https://github.com/Moving-Castles/this-cursed-machine/assets/17074938/61d5bf86-0f93-49fe-86bf-acf5f32ace62)

Fixed
