### ISSUE TITLE
Depot amounts are not calculated correctly when using two inlets

### ISSUE THREAD

**Issue by pwrstudio** [Moving-Castles/this-cursed-machine#177]
![Image](https://github.com/Moving-Castles/this-cursed-machine/assets/8209990/c10d7204-f189-4ee6-9745-6b65b1821ae3)

**Comment by manegame** [comment]
This network turned 100 bugs into 50 hematuric fluid


![Image](https://github.com/Moving-Castles/this-cursed-machine/assets/17074938/e9ceabff-90c2-4eda-85f9-6fc095190470)
