### ISSUE TITLE
Graph and terminal only loads for first spawned player

### ISSUE THREAD

**Issue by pwrstudio** [Moving-Castles/this-cursed-machine#4]
For example:
- starting on local deployment in normal browser works.
- starting as a second player in incognito does not

Various errors:

<img width="906" alt="Screenshot 2023-10-10 at 11 28 37" src="https://github.com/Moving-Castles/this-cursed-machine/assets/8209990/c9be1356-a2be-420e-9a8c-8feb4a7f6802">

![IMAGE 2023-10-10 11:30:58](https://github.com/Moving-Castles/this-cursed-machine/assets/8209990/b01cfa4a-225e-4a2b-b07a-7d28e9148e1f)

![IMAGE 2023-10-10 11:31:04](https://github.com/Moving-Castles/this-cursed-machine/assets/8209990/c6577406-4199-4ba7-aaf8-72df3f12464b)

**Comment by pwrstudio** [comment]
Same happens on respawn.

**Comment by manegame** [comment]
Should now be fixed. Testing more before I close
